---
Name: silverstripe-algolia
After: 'framework/*','cms/*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
   - Wilr\SilverStripe\Algolia\AlgoliaSiteConfigExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Wilr\SilverStripe\Algolia\AlgoliaSiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Wilr\SilverStripe\Algolia\Extensions\SiteTreeExtension
