---
Name: silverstripe-search-service
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\SearchService\Extensions\SearchServiceExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\SearchService\Extensions\SearchServiceExtension:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
  SilverStripe\SearchService\Tasks\SearchConfigure:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
  SilverStripe\SearchService\Tasks\SearchReindex:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
  SilverStripe\SearchService\Tasks\SearchInspect:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
  SilverStripe\SearchService\Service\DocumentFetcherRegistry:
    constructor:
      dataObject: '%$SilverStripe\SearchService\DataObject\DataObjectFetcher`



---
Name: silverstripe-search-service-appsearch
Only:
  envvarset: 'APP_SEARCH_API_KEY'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SearchService\Interfaces\SearchServiceInterface:
    class: SilverStripe\SearchService\Services\AppSearch\AppSearchService
    constructor:
      client: '%$Elastic\AppSearch\Client\Client'
  Elastic\AppSearch\Client\Client:
    factory: SilverStripe\SearchService\Services\AppSearch\ClientFactory
    constructor:
      endpoint: '`APP_SEARCH_ENDPOINT`'
      apiKey: '`APP_SEARCH_API_KEY`'
