---
Name: silverstripe-search-service
---
SilverStripe\Core\Injector\Injector:

  SilverStripe\SearchService\Extensions\SearchServiceExtension:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      batchProcessor: '%$SilverStripe\SearchService\Service\BatchProcessor'

  SilverStripe\SearchService\Tasks\SearchConfigure:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'

  SilverStripe\SearchService\Tasks\SearchReindex:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      batchProcessor: '%$SilverStripe\SearchService\Service\BatchProcessor'

  SilverStripe\SearchService\Tasks\SearchInspect:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'

  SilverStripe\SearchService\Service\DocumentFetchCreatorRegistry:
    constructor:
      dataObject: '%$SilverStripe\SearchService\DataObject\DataObjectFetchCreator'

  SilverStripe\SearchService\Service\BatchProcessor:
    constructor:
      searchService: '%$SilverStripe\SearchService\Interfaces\SearchServiceInterface'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'

  SilverStripe\SearchService\Service\IndexConfiguration:
    constructor:
      index_variant: '`SS_ENVIRONMENT_TYPE`'
